server:
  port: 803

spring:
  application:
    name: localhost

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${spring.application.name}:${server.port}/eureka/