server:
  port: 80

eureka:
  instance:
    hostname: peer3
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka.peer1/eureka/,http://eureka.peer2/eureka/